apiVersion: apps/v1
kind: Deployment
metadata:
  name: happiness-score
  annotations:
    # dev.okteto.com/path: okteto.yml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happiness-score
  template:
    metadata:
      labels:
        app: happiness-score
    spec:
      containers:
      - image: registry.cloud.okteto.net/thapakazi/custom/happiness-score:latest
        name: happiness-score
        envFrom:
          - secretRef:
              name: happiness-score
        ports:
          - containerPort: 8080
            name: apiport
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: happiness-score
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "happiness-score"
    port: 8080
  selector:
    app: happiness-score
