# File: .github/workflows/workflow.yml
on: [push]

name: example

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: thapakazi
    
    # - name: "Build"
    #   uses: okteto/actions/build@master
    #   with:
    #     tag: registry.cloud.okteto.net/thapakazi/happiness_score:latest
    - name: "Debug"
      run: |
        ls -la $GITHUB_WORKSPACE
        docker images
        pwd
        env

    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: thapakazi
        name: happiness_score

    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: thapakazi
        manifest: $GITHUB_WORKSPACE/deploy/k8s.yml
  
