# File: .github/workflows/workflow.yml
on:
  push:
    branches:
      - master

name: Test and Deploy

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running test
        run: |
          cat /etc/os-release
          ps -aux
          uptime
          echo "testing this that"
  
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@master
      with:
        name: thapakazi
    
    # - name: "Build"
    #   uses: okteto/actions/build@master
    #   with:
    #     tag: registry.cloud.okteto.net/thapakazi/happiness-score:latest
    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: thapakazi
        manifest: deploy/k8s.yml

    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: thapakazi
        name: happiness-score
        working-directory: api
